### ISSUE TITLE
Shields damaged despite target having immunity

### ISSUE THREAD

**Issue by mevitar** [Phobos-developers/Phobos#1130]
### Description

The TypeImmune=yes and Immune=yes tags do not prevent shields from being damaged. This is the case ever since shield code was rewritten (to fix the cloak bug?).

AffectsAllies=no on the warhead works properly and does not damage the shields of friendly objects.
DamageSelf=no is still respected and will not damage the shield of the firer.

### Phobos Version

https://github.com/Phobos-developers/Phobos/commit/f100ed8d895c087413f50a4ab6297b22195fda23

### Steps to reproduce

1. Give a unit with shield TypeImmune=yes and an AreaFire=yes weapon.
2. Order that unit to attack another unit of its type.
3. !?!?
4. Go to Phobos bug page to report a bug.

### Expected behaviour

TypeImmune=yes and Immune=yes should prevent shields from being damaged.

### Actual behaviour

Immune=yes objects cannot be attacked, yet their shields are still damaged if they are within the warhead's detonation radius.
TypeImmune=yes does not prevent objects from damaging the shields of other objects of that type.

### Checklist

- [X] The issue happens on the **latest official** version of Phobos and wasn't fixed yet.
- [X] I agree to elaborate the details if requested and provide thorough testing if the bugfix is implemented.
- [X] I added a very descriptive title to this issue.
- [X] I used the GitHub search and read the issue list to find a similar issue and didn't find it.
- [X] I have attached as much information as possible *(screenshots, gifs, videos, debug and exception logs, etc)*.

**Comment by Starkku** [comment]
Currently damage is passed to shield logic raw before any other logic or checks at `TechnoClass` level is applied to it. This means no `TypeImmune` or armor modifiers from veterancy, crates etc. or `Immune` (which is checked much later) for an instance but things like `ProneDamage`, `DamageSelf` and `Sonic=true` parasite removal are applied since they are done at a higher level.

Shield logic itself checks temporal, IC and `AffectsAllies/Owner/Enemies` and adding bespoke check for `Immune` or `TypeImmune` would be easy to add, although question lingers if this (and possibly the iron curtain check) should be customizable for shields to some degree or if such thing isn't really necessary.

**Comment by mevitar** [comment]
Personally i don't see a reason for why someone would want to make something that is completely immune to damage have shields that can be damaged (tbh i don't think there's a reason to give such objects shields in the first place).

I can think of cases where a shield could be used to prevent a weapon from reducing the IC timer, but i suppose that might be out of the question anyway since IC timers are an Ares thing. Don't think it would be needed for anything else.

I can also see someone wanting to make TypeImmune=yes objects still damage their own shields when firing, but then, same can be said about ImmuneToPsionics, ImmuneToRadiation, ImmuneToPoison, Parasiteable, Warpable etc. If TypeImmune can be customized per shield, shouldn't those be added too?
Nah, i think those are fine to be customizable just for the owner of the shield, not shields.

**Comment by mevitar** [comment]
Fixed. No issues found.
